import { AsmrToy, AsmrToyCategory } from '../../domain/models/AsmrToy';

export const DEFAULT_ASMR_TOYS: readonly AsmrToy[] = [
  new AsmrToy({
    id: 'toy_bubble_wrap',
    name: 'ぷちぷちバブルラップ',
    description: '気泡をつぶしてポコポコ爽快！タップするたび心地よいパチン音。',
    soundType: 'bubble_wrap',
    unlockCost: 0,
    baseCoinYield: 1,
    icon: '🫧',
    category: AsmrToyCategory.TACTILE,
  }),
  new AsmrToy({
    id: 'toy_soap_cutting',
    name: 'サクサク石鹸カット',
    description: 'スワイプで色とりどりの石鹸キューブを削る、至高のサクサク音。',
    soundType: 'soap_cutting',
    unlockCost: 50,
    baseCoinYield: 3,
    icon: '🧼',
    category: AsmrToyCategory.TACTILE,
  }),
  new AsmrToy({
    id: 'toy_potato_chips',
    name: 'パリパリポテトチップス',
    description: 'ザクッ！パリッ！と香ばしい咀嚼音がたまらない大人気ASMR。',
    soundType: 'potato_chips',
    unlockCost: 120,
    baseCoinYield: 5,
    icon: '🥔',
    category: AsmrToyCategory.FOOD,
  }),
  new AsmrToy({
    id: 'toy_shaved_ice',
    name: 'シャリシャリかき氷',
    description: 'ひんやり冷たい氷の結晶を削る、爽快シャリシャリスプーン音。',
    soundType: 'shaved_ice',
    unlockCost: 250,
    baseCoinYield: 8,
    icon: '🍧',
    category: AsmrToyCategory.FOOD,
  }),
  new AsmrToy({
    id: 'toy_slime',
    name: 'むにむにスライム',
    description: '指でこねて広げる、ぷるぷる＆ウェットな癒やしのむにゅ音。',
    soundType: 'slime',
    unlockCost: 500,
    baseCoinYield: 12,
    icon: '🟢',
    category: AsmrToyCategory.TACTILE,
  }),
  new AsmrToy({
    id: 'toy_keyboard',
    name: 'カチカチキーボード',
    description: 'メカニカルキースイッチの心地よいタイピング音とコトコト反響音。',
    soundType: 'keyboard',
    unlockCost: 900,
    baseCoinYield: 18,
    icon: '⌨️',
    category: AsmrToyCategory.TACTILE,
  }),
  new AsmrToy({
    id: 'toy_carbonated_soda',
    name: 'シュワシュワ炭酸水',
    description: 'グラスの中で無数の微小気泡がシュワッと弾ける極上の爽快感。',
    soundType: 'carbonated_soda',
    unlockCost: 1500,
    baseCoinYield: 25,
    icon: '🥤',
    category: AsmrToyCategory.FOOD,
  }),
  new AsmrToy({
    id: 'toy_scissors_haircut',
    name: 'チョキチョキ美容室',
    description: '耳元で研ぎ澄まされたハサミが小気味よく開閉するシャープな刃音。',
    soundType: 'scissors_haircut',
    unlockCost: 2400,
    baseCoinYield: 35,
    icon: '✂️',
    category: AsmrToyCategory.RELAX,
  }),
  new AsmrToy({
    id: 'toy_book_page_flip',
    name: 'パラパラ古本めくり',
    description: '静かな図書館で乾いた紙が重なり合い、めくられていく優しい擦過音。',
    soundType: 'book_page_flip',
    unlockCost: 3800,
    baseCoinYield: 50,
    icon: '📖',
    category: AsmrToyCategory.RELAX,
  }),
  new AsmrToy({
    id: 'toy_autumn_leaves',
    name: 'ザクザク落ち葉踏み',
    description: '秋の木漏れ日の中、乾燥した落ち葉を靴底で踏みしめるザクザク感。',
    soundType: 'autumn_leaves',
    unlockCost: 6000,
    baseCoinYield: 70,
    icon: '🍂',
    category: AsmrToyCategory.NATURE,
  }),
  new AsmrToy({
    id: 'toy_wood_block_clack',
    name: 'カンカン木製ブロック',
    description: '中空の堅木ブロックを叩く、乾いた高音と温かみのあるポクポク響き。',
    soundType: 'wood_block_clack',
    unlockCost: 9500,
    baseCoinYield: 95,
    icon: '🪵',
    category: AsmrToyCategory.TACTILE,
  }),
  new AsmrToy({
    id: 'toy_match_ignite',
    name: 'シュッ！マッチ着火',
    description: '箱の側面にマッチ棒を擦り、シュッと炎が燃え上がる瞬間ノイズ。',
    soundType: 'match_ignite',
    unlockCost: 15000,
    baseCoinYield: 130,
    icon: '🔥',
    category: AsmrToyCategory.RELAX,
  }),
  new AsmrToy({
    id: 'toy_rain_umbrella',
    name: 'しとしと雨の傘',
    description: 'ビニール傘や布傘の表面にぽつぽつ優しく当たる天然のホワイトノイズ。',
    soundType: 'rain_umbrella',
    unlockCost: 24000,
    baseCoinYield: 180,
    icon: '☔',
    category: AsmrToyCategory.NATURE,
  }),
  new AsmrToy({
    id: 'toy_clock_tick',
    name: 'コチコチ古時計',
    description: 'アンティーク振り子時計が正確に刻む、静かな夜のコチコチ音。',
    soundType: 'clock_tick',
    unlockCost: 38000,
    baseCoinYield: 250,
    icon: '🕰️',
    category: AsmrToyCategory.RELAX,
  }),
  new AsmrToy({
    id: 'toy_water_drop_cave',
    name: 'ポタポタ洞窟の水滴',
    description: '青く澄んだ洞窟の地底湖に一筋落ちる、澄み切ったピチャンという水滴。',
    soundType: 'water_drop_cave',
    unlockCost: 60000,
    baseCoinYield: 350,
    icon: '💧',
    category: AsmrToyCategory.NATURE,
  }),
  new AsmrToy({
    id: 'toy_fire_crackling',
    name: 'パチパチ焚き火',
    description: '夜風に揺れるキャンプファイヤーで薪の樹液がパチッとはぜる癒やし音。',
    soundType: 'fire_crackling',
    unlockCost: 95000,
    baseCoinYield: 500,
    icon: '🏕️',
    category: AsmrToyCategory.NATURE,
  }),
  new AsmrToy({
    id: 'toy_whisper_ear_pick',
    name: 'ふわふわ梵天耳かき',
    description: 'ふわふわの白い羽毛や綿毛が耳の奥を撫でる、超極楽のリフレッシュ音。',
    soundType: 'whisper_ear_pick',
    unlockCost: 150000,
    baseCoinYield: 750,
    icon: '👂',
    category: AsmrToyCategory.RELAX,
  }),
  new AsmrToy({
    id: 'toy_cat_purr',
    name: 'ゴロゴロ猫ののど鳴らし',
    description: '膝の上で甘える猫ちゃんが胸の奥から響かせる温かいゴロゴロ低周波。',
    soundType: 'cat_purr',
    unlockCost: 250000,
    baseCoinYield: 1100,
    icon: '🐾',
    category: AsmrToyCategory.RELAX,
  }),
  new AsmrToy({
    id: 'toy_bell_wind_chime',
    name: 'チリンチリン南部風鈴',
    description: '夏の軒先で涼やかな微風に揺れる、透き通った金属風鈴の美しい余韻。',
    soundType: 'bell_wind_chime',
    unlockCost: 400000,
    baseCoinYield: 1600,
    icon: '🎐',
    category: AsmrToyCategory.RELAX,
  }),
  new AsmrToy({
    id: 'toy_crystal_tap',
    name: 'きらめく神秘クリスタル',
    description: '神秘的なアメジスト宝石を指先でタップし、澄んだ倍音ハーモニーを共鳴。',
    soundType: 'crystal_tap',
    unlockCost: 650000,
    baseCoinYield: 2500,
    icon: '💎',
    category: AsmrToyCategory.NATURE,
  }),
];
